project/project/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace project.Models
{
    public class Hotel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [MaxLength(255)]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required]
        [MaxLength(50)]
        public string City { get; set; }

        [Required]
        [Range(1,5)]
        public int Stars { get; set; }

        public string urlToImage { get; set; }

        public List<Room> AllRooms { get; set; }

    }
}

project/project/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using project.Data;
using project.Models;
using project.Models.AccountViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace project.Controllers
{
    [Authorize]
    public class HotelController : Controller
    {
        private readonly ApplicationDbContext _context;

        private UserManager<ApplicationUser> _userManager;

        private SignInManager<ApplicationUser> _signInManager;

        public HotelController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        //get that one hotel
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> HotelIndex(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels
                .SingleOrDefaultAsync(item => item.Id == id);

            if(hotel == null)
            {
                return NotFound();
            }

            var rooms = await _context.Rooms.ToListAsync();
            ViewBag.Rooms = rooms.FindAll(item => item.HotelId == id);
           
            return View(hotel);
        }

        [HttpGet]
        public async Task<IActionResult> BookRoom(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var rooms = await _context.Rooms.ToListAsync();

            var room = rooms.SingleOrDefault(item => item.RoomId == id);

            ViewBag.Room = room;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookRoom(int? roomId, Booking booking)
        {
            var hotel = await _context.Rooms.SingleOrDefaultAsync(r => r.RoomId == roomId);

            int hotelId = hotel.HotelId;

            if (roomId == null)
            {
                return RedirectToAction(nameof(HotelIndex), new { id = hotelId });
            }
            
            if (ModelState.IsValid)
            {
                var id = -1;
                DateTime startDate = booking.StartDate;
                DateTime endDate = booking.EndDate;

                if(startDate <= DateTime.Today || startDate > endDate)
                {
                    ViewBag.Status = "Wrong dates";
                    return View(booking);
                }

                var activeBookings = _context.Bookings.Where(booking => booking.IsActive);
                var rooms = _context.Rooms;

                foreach(var room in rooms)
                {
                    var activeBookingsForRoom = activeBookings.Where(booking => booking.RoomId == roomId);
                    if(activeBookingsForRoom.All(b => startDate < b.StartDate &&
                        endDate < b.StartDate || startDate > b.EndDate && endDate > b.EndDate))
                    {
                        id = room.RoomId;
                        break;
                    }
                }

                if(id >= 0)
                {
                    var user = await _userManager.GetUserAsync(User);

                    booking.CustomerId = user.Id;
                    booking.RoomId = id;
                    booking.IsActive = true;
                    _context.Bookings.Add(booking);
                    await _context.SaveChangesAsync();
                    TempData["Message"] = "Room booked successfully";
                    return RedirectToAction(nameof(HotelIndex), new { id = hotelId });
                }
            }

            var allRooms = await _context.Rooms.ToListAsync();

            var roomToPass = allRooms.SingleOrDefault(item => item.RoomId == roomId);

            ViewBag.Status = "The booking could not be created. There were no available room.";
            ViewBag.Room = roomToPass;
            return RedirectToAction(nameof(HotelIndex), new { id = hotelId });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteBooking(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.SingleOrDefaultAsync(item => item.Id == id);

            if(booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.SingleOrDefaultAsync(item => item.Id == id);

            if (booking == null)
            {
                return NotFound();
            }

            _context.Bookings.Remove(booking);

            var result = await _context.SaveChangesAsync();

            if (result == 0)
            {
                TempData["Message"] = "There was a problem while deleting user";
                return RedirectToAction(nameof(HotelIndex));
            }

            TempData["Message"] = "Account has been deleted successfully";
            return RedirectToAction(nameof(HotelIndex));
        }
    }
}

project/project/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using project.Data;
using project.Models;
using project.Models.AccountViewModels;

namespace project.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;

        private UserManager<ApplicationUser> _userManager;

        private SignInManager<ApplicationUser> _signInManager;

        public ProfileController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var allBookings = await _context.Bookings.ToListAsync();

            allBookings = allBookings.FindAll(b => b.CustomerId == user.Id);

            return View(allBookings);
        }

        [HttpGet]
        public ActionResult EditProfile()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProfile([Bind("FirstName, LastName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                var _user = await _userManager.GetUserAsync(User);
                _user.FirstName = applicationUser.FirstName;
                _user.LastName = applicationUser.LastName;

                var result = await _userManager.UpdateAsync(_user);
                if (result.Succeeded)
                {
                    TempData["Message"] = "Profile edited successfully";
                    return RedirectToAction(nameof(Index));
                }
                AddErrors(result);
            }
            // whopsie
            return View();
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword([Bind("newPassword, newPasswordConfirm")] ChangePasswordViewModel applicationUser)
        {
            if (ModelState.IsValid)
            {
                if(applicationUser.newPassword == applicationUser.newPasswordConfirm)
                {
                    var user = await _userManager.GetUserAsync(User);

                    var token = await _userManager.GeneratePasswordResetTokenAsync(user);

                    var result = await _userManager.ResetPasswordAsync(user, token, applicationUser.newPassword);

                    if (result.Succeeded)
                    {
                        TempData["Message"] = "Password has been changed successfully";
                        return RedirectToAction(nameof(Index));
                    }

                    AddErrors(result);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Passwords do not match");
                }
            }
            return View();
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

project/project/Views/Hotel/BookRoom.cshtml
@model project.Models.Booking
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Book Room";
    Room room = ViewBag.Room;
}

@*<h2>Create</h2>
<h4 class="text-danger">@ViewBag.Status</h4>
<h4>Booking</h4>*@

<div class="hotelHeader" style="background-image: url('@room.urlToImage');">
    <div class="hotelHeaderAlpha">
        <p class="hotelHeaderName">Book choosen room</p>
    </div>
</div>

<hr />
<div class="bookPage">
        <form asp-action="BookRoom" asp-route-roomid="@room.RoomId">
            <div class="dateContainer">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate" class="control-label"></label>
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>
            @*<div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <select asp-for="RoomId" class="form-control" asp-items="ViewBag.RoomId"></select>
            </div>*@
            <div class="bookButton">
                <input type="submit" value="Book" class="btn btn-default" />
            </div>
        </form>
</div>

project/project/Views/Hotel/DeleteBooking.cshtml
@model project.Models.Booking

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Delete Worker";
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Worker</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>

    <form asp-action="Delete" method="post" asp-route-id="@Model.Id">
        @*<input type="hidden" asp-for="Id" />*@
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-controller="Profile" asp-action="Index">Back to List</a>
    </form>
</div>

project/project/Views/Hotel/HotelIndex.cshtml
@model project.Models.Hotel

@{
    var HotelName = Model.Name;
    ViewData["Title"] = HotelName;
    List<project.Models.Room> rooms = ViewBag.Rooms;

    var tempMessage = (string)TempData["Message"];
}

<div class="hotelHeader" style="background-image: url('@Html.DisplayFor(model => model.urlToImage)');">
    <div class="hotelHeaderAlpha">
        <p class="hotelHeaderName">@Html.DisplayFor(model => model.Name)</p>
    </div>
</div>

<div>
    @if (tempMessage != null)
    {
        <div>
            <h2 style="margin: 0 auto;">@tempMessage</h2>
        </div>
    }
    @*<div>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div>
            @Html.DisplayFor(model => model.Stars) Stars
        </div>

        <div>
            Total rooms count @rooms.Count()
        </div>*@

    <div class="roomsContainer">
        @foreach (var item in rooms)
        {


            string stars = new String('⭑', item.StandardQuality);


            <div class="roomContainer" style="background-image: url('@item.urlToImage');">
                <div class="roomContainerAlpha">
                    <a class="hotelName" asp-controller="Hotel" asp-action="BookRoom" asp-route-id="@item.RoomId">
                        @stars
                        <br />
                        @item.PricePerNight PLN
                    </a>
                </div>
            </div>
        }
    </div>

    @*@foreach (var item in rooms)
        {
            <div>
                Room number : @item.RoomNumber
            </div>
            <div>
                Quality type : @item.StandardQuality
            </div>
        }*@
    @*<a asp-controller="Hotel" asp-action="BookRoom" asp-route-id="@Model.Id"> Book Room </a>*@
</div>