project/project/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace project.Models
{
    public class Message
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [MaxLength(255)]
        public string MessageContent { get; set; }

        public string FromEmail { get; set; }

        public string ToEmail { get; set; }

        public bool isToWorker { get; set; }

        public DateTime DateTime { get; set; }

        public bool isAnswer { get; set; }

        public bool isAnswered { get; set; }
    
        public int isAnswerTo { get; set; }

    }
}

project/project/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using project.Models;
using project.Models.AccountViewModels;
using project.Data;
using Microsoft.EntityFrameworkCore;

namespace project.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private ApplicationDbContext _context;

        private UserManager<ApplicationUser> _userManager;

        private SignInManager<ApplicationUser> _signInManager;

        public AdminController(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            if(!(await checkIfAdmin()))
            {
                RedirectHome();
            }

            var listAllWorkers = await _context.Users.Where(u => u.isSuperAdmin == false).Where(u => u.isWorker == true).ToListAsync();

            return View(listAllWorkers);
        }

        [HttpGet]
        public async Task<ActionResult> CreateNewAccount()
        {
            if (!(await checkIfAdmin()))
            {
                RedirectHome();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNewAccount([Bind()]RegisterWorkerViewModel model)
        {

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email, FirstName = model.FirstName, LastName = model.LastName, isWorker = true };
                var defaultPassword = "Password123$";
                var result = await _userManager.CreateAsync(user, defaultPassword);
                if (result.Succeeded)
                {
                    TempData["Message"] = "Account has been created successfully";
                    return RedirectToAction(nameof(Index));
                }
                AddErrors(result);
            }

            //Whopsiee
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteWorker(string id)
        {
            if (!(await checkIfAdmin()))
            {
                RedirectHome();
            }

            if (id == null)
            {
                return NotFound();  
            }

            var worker = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id, string email)
        {
            var u = await _userManager.FindByIdAsync(id);
            var u2 = await _userManager.FindByEmailAsync(email);

            if (!(await checkIfAdmin()))
            {
                RedirectHome();
            }

            var worker = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(worker);
            var result = await _context.SaveChangesAsync();

            if (result == 0)
            {
                TempData["Message"] = "There was a problem while deleting user";
                return RedirectToAction(nameof(Index));
            }

            TempData["Message"] = "Account has been deleted successfully";
            return RedirectToAction(nameof(Index));
            
        }

        private async Task<bool> checkIfAdmin()
        {
            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);
                if (user.isSuperAdmin)
                {
                    return true;
                }
            }
            return false;
        }

        private IActionResult RedirectHome()
        {
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

project/project/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using project.Data;
using project.Models;
using project.Models.AccountViewModels;


namespace project.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private ApplicationDbContext _context;

        private UserManager<ApplicationUser> _userManager;

        private SignInManager<ApplicationUser> _signInManager;

        public MessagesController(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);

                var allMessages = await _context.Messages.ToListAsync();

                if (user.isWorker || user.isSuperAdmin)
                {
                    allMessages = allMessages.FindAll(m => m.isToWorker);
                }
                else
                {
                    allMessages = allMessages.FindAll(m => !m.isToWorker);

                }

                allMessages = allMessages.FindAll(m => !m.isAnswered);

                return View(allMessages);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> AllMessages()
        {
            var user = await _userManager.GetUserAsync(User);

            var allMessages = await _context.Messages.ToListAsync();

            allMessages = allMessages.FindAll(m => m.ToEmail == user.Email);

            return View(allMessages);
        }

        [HttpGet]
        public async Task<IActionResult> AnswerMessage(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.SingleOrDefaultAsync(m => m.Id == id);

            if(message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AnswerMessage(Message message)
        { 
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);

                Message newMessage = new Message
                {
                    DateTime = DateTime.Now,
                    FromEmail = user.Email,
                    isToWorker = !user.isWorker,
                    isAnswer = true,
                    isAnswerTo = message.Id,
                    MessageContent = message.MessageContent,
                    ToEmail = message.FromEmail,
                    isAnswered = true
                };

                await _context.Messages.AddAsync(newMessage);

                var result = await _context.SaveChangesAsync();

                if(result > 0)
                {
                    var msg = await _context.Messages.SingleOrDefaultAsync(m => m.Id == message.Id);

                    msg.isAnswered = true;

                    await _context.SaveChangesAsync();

                    TempData["Message"] = "Message sent successfully";
                }
                else
                {
                    TempData["Message"] = "There was a problem answering";
                }
                return RedirectToAction(nameof(Index));

            }

            return View(message);
        }

        [HttpGet]
        public async Task<IActionResult> NewMessage()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewMessage([Bind("MessageContent")] Message message)
        {
            var user = await _userManager.GetUserAsync(User);

            message.DateTime = DateTime.Now;
            message.FromEmail = user.Email;
            message.isAnswer = false;
            message.isToWorker = false;
            message.ToEmail = "";
            message.isAnswered = false;

            if (ModelState.IsValid)
            {
                if(user.isWorker)
                {
                    var allUsers = await _context.Users.ToListAsync();

                    allUsers = allUsers.FindAll(u => !u.isWorker && !u.isSuperAdmin);

                    allUsers.ForEach(async (item) =>
                    {
                       var newMessage = message;
                       message.ToEmail = item.Email;
                       await _context.Messages.AddAsync(newMessage);
                    });
                }
                else
                {
                    message.isToWorker = true;
                    await _context.Messages.AddAsync(message);
                }

                var result = await _context.SaveChangesAsync();
                if(result > 0)
                {
                    TempData["Message"] = "Message sent successfully";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Something went wrong");
                    return View(message);
                }
            }
            return View();
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

project/project/Views/Messages/AllMessages.cshtml
@using Microsoft.AspNetCore.Identity
@using project.Models

@model IEnumerable<project.Models.Message>
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "All Messages";
}

<div>
    <h2>All old messages </h2>
    @if (Model.Count() != 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Message
                    </th>
                    <th>
                        From
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MessageContent)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FromEmail)
                        </td>
                    </tr>
                }
            </tbody>

        </table>

    }
    else
    {
        <p>You don't have any messages</p>
    }

    <a asp-controller="Messages" asp-action="Index" > Go back </a>
</div>

project/project/Views/Messages/AnswerMessage.cshtml
@using Microsoft.AspNetCore.Identity
@using project.Models

@model project.Models.Message
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Answer Message";
}

<div>
    <h2> Message Content</h2>

    <p>@Model.MessageContent</p>
    <form asp-controller="Messages" asp-action="AnswerMessage" method="post" style="width:350px">
        <hr />
        <div class="form-group">
            <label asp-for="MessageContent" style="width:185px; display:inline-block;"></label>
            <input asp-for="MessageContent" class="form-control" value="" />
            <span asp-validation-for="MessageContent" class="text-danger"></span>
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>

        <button type="submit" class="btn btn-default" style="float:right;">Answer</button>
        <a asp-action="Index" asp-controller="Admin">Go back to messages</a>
    </form>
</div>

project/project/Views/Messages/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using project.Models

@model IEnumerable<project.Models.Message>
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Messages";

    var user = await UserManager.GetUserAsync(User);

    var isWorker = user.isWorker || user.isSuperAdmin;
}

<div>
    <a asp-controller="Messages" asp-action="NewMessage">Send a new message</a>

    @if (Model.Count() != 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Message
                    </th>
                    @if (isWorker)
                    {
                        <th>
                            From
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MessageContent)
                    </td>
                @if (isWorker)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.FromEmail)
                    </td>
                }
                    <td>
                        <a asp-action="AnswerMessage" asp-route-id="@item.Id"> Answer </a>
                    </td>
                </tr>
                }
            </tbody>

        </table>

    }
    else
    {
        <p>You don't have any messages</p>
    }
</div>

project/project/Views/Messages/NewMessage.cshtml
@using Microsoft.AspNetCore.Identity
@using project.Models

@model project.Models.Message
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Messages";

    var user = await UserManager.GetUserAsync(User);

    var isWorker = user.isWorker || user.isSuperAdmin;

}

<div>

    <form asp-controller="Messages" asp-action="NewMessage" method="post" style="width:350px">
        <h4>Send a new message</h4>
        <hr />
        <input asp-for="Id" type="hidden" />
        <input asp-for="isAnswer" type="hidden" value="no" />
        <input asp-for="FromEmail" type="hidden" value="@user.Email" />

        @if (isWorker)
        {
            <h6>The message will be sent to everyone.</h6>
        }
        else
        {
            <h6>This message will be sent to workers</h6>
        }

        <div class="form-group">
            <label asp-for="MessageContent" style="width:185px; display:inline-block;"></label>
            <input asp-for="MessageContent" class="form-control" />
            <span asp-validation-for="MessageContent" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-default" style="float:right;">Create</button>
        <a asp-controller="Messages" asp-action="Index" >Go back</a>
    </form>

</div>